### ISSUE TITLE
How to lookup podcast episodes

### ISSUE THREAD

**Issue by mshd** [marcbouchenoire/itunes-store-api#32]
I'm having trouble getting a list of episodes:
This is the url I want to query
https://itunes.apple.com/lookup?id=1251196416&country=US&media=podcast&entity=podcastEpisode&limit=100

this does not seem to work with "await lookup("id", playlistId, "podcast");"

**Comment by marcbouchenoire** [comment]
The third argument doesn't accept a string, it's an `options` object and currently it only supports a `"country"` option on `lookup`. `"media"`, `"entity"` and others are already supported on `search` and I've been meaning to add them to `lookup` as well but haven't got to it yet.

**Comment by marcbouchenoire** [comment]
It's now possible to set options on `lookup` as well:

```ts
await lookup("id", 1251196416, { entity: "podcast" })
```
